
// ------------------- PRODUCT -------------------
//get-product
export const GET_PRODUCT_PENDING = " GET_PRODUCT_PENDING"
export const GET_PRODUCT_SUCCESS =" GET_PRODUCT_SUCCESS"
export const GET_PRODUCT_ERROR = " GET_PRODUCT_ERROR"
//post-product
export const POST_PRODUCT_PENDING = " POST_PRODUCT_PENDING"
export const POST_PRODUCT_SUCCESS =" POST_PRODUCT_SUCCESS"
export const POST_PRODUCT_ERROR = " POST_PRODUCT_ERROR"
//delete-product
export const DELETE_PRODUCT_PENDING = " DELETE_PRODUCT_PENDING"
export const DELETE_PRODUCT_SUCCESS =" DELETE_PRODUCT_SUCCESS"
export const DELETE_PRODUCT_ERROR = " DELETE_PRODUCT_ERROR"
// update-product
export const UPDATE_PRODUCT_PENDING = " UPDATE_PRODUCT_PENDING"
export const UPDATE_PRODUCT_SUCCESS =" UPDATE_PRODUCT_SUCCESS"
export const UPDATE_PRODUCT_ERROR = " UPDATE_PRODUCT_ERROR"



// ------------------- CATEGORY -------------------
//get-category
export const GET_CATEGORY_PENDING = " GET_CATEGORY_PENDING"
export const GET_CATEGORY_SUCCESS =" GET_CATEGORY_SUCCESS"
export const GET_CATEGORY_ERROR = " GET_CATEGORY_ERROR"
//post-category
export const POST_CATEGORY_PENDING = " POST_CATEGORY_PENDING"
export const POST_CATEGORY_SUCCESS =" POST_CATEGORY_SUCCESS"
export const POST_CATEGORY_ERROR = " POST_CATEGORY_ERROR"
//delete-category
export const DELETE_CATEGORY_PENDING = " DELETE_CATEGORY_PENDING"
export const DELETE_CATEGORY_SUCCESS =" DELETE_CATEGORY_SUCCESS"
export const DELETE_CATEGORY_ERROR = " DELETE_CATEGORY_ERROR"
// update-category 
export const UPDATE_CATEGORY_PENDING = " UPDATE_CATEGORY_PENDING"
export const UPDATE_CATEGORY_SUCCESS =" UPDATE_CATEGORY_SUCCESS"
export const UPDATE_CATEGORY_ERROR = " UPDATE_CATEGORY_ERROR"



// ------------------- BRAND -------------------
//get-brand
export const GET_BRAND_PENDING = " GET_BRAND_PENDING"
export const GET_BRAND_SUCCESS =" GET_BRAND_SUCCESS"
export const GET_BRAND_ERROR = " GET_BRAND_ERROR"
//post-brand
export const POST_BRAND_PENDING = " POST_BRAND_PENDING"
export const POST_BRAND_SUCCESS =" POST_BRAND_SUCCESS"
export const POST_BRAND_ERROR = " POST_BRAND_ERROR"
//delete-brand
export const DELETE_BRAND_PENDING = " DELETE_BRAND_PENDING"
export const DELETE_BRAND_SUCCESS =" DELETE_BRAND_SUCCESS"
export const DELETE_BRAND_ERROR = " DELETE_BRAND_ERROR"
// update-brand 
export const UPDATE_BRAND_PENDING = " UPDATE_BRAND_PENDING"
export const UPDATE_BRAND_SUCCESS =" UPDATE_BRAND_SUCCESS"
export const UPDATE_BRAND_ERROR = " UPDATE_BRAND_ERROR"



// ------------------- MODEL -------------------
//get-model
export const GET_MODEL_PENDING = " GET_MODEL_PENDING"
export const GET_MODEL_SUCCESS =" GET_MODEL_SUCCESS"
export const GET_MODEL_ERROR = " GET_MODEL_ERROR"
//post-model
export const POST_MODEL_PENDING = " POST_MODEL_PENDING"
export const POST_MODEL_SUCCESS =" POST_MODEL_SUCCESS"
export const POST_MODEL_ERROR = " POST_MODEL_ERROR"
//delete-model
export const DELETE_MODEL_PENDING = " DELETE_MODEL_PENDING"
export const DELETE_MODEL_SUCCESS =" DELETE_MODEL_SUCCESS"
export const DELETE_MODEL_ERROR = " DELETE_MODEL_ERROR"
// update-model 
export const UPDATE_MODEL_PENDING = " UPDATE_MODEL_PENDING"
export const UPDATE_MODEL_SUCCESS =" UPDATE_MODEL_SUCCESS"
export const UPDATE_MODEL_ERROR = " UPDATE_MODEL_ERROR"
