import { all } from 'redux-saga/effects'
import {
    HANDLE_DELETE_BRAND_SAGA, HANDLE_DELETE_CATEGORY_SAGA, HANDLE_DELETE_MODEL_SAGA, HANDLE_DELETE_PRODUCT_SAGA,
    HANDLE_GET_BRAND_SAGA, HANDLE_GET_CATEGORY_SAGA, HANDLE_GET_MODEL_SAGA, HANDLE_GET_PRODUCT_SAGA, 
    HANDLE_POST_BRAND_SAGA, HANDLE_POST_CATEGORY_SAGA, HANDLE_POST_MODEL_SAGA, HANDLE_POST_PRODUCT_SAGA, 
    HANDLE_UPDATE_BRAND_SAGA, HANDLE_UPDATE_CATEGORY_SAGA, HANDLE_UPDATE_MODEL_SAGA, HANDLE_UPDATE_PRODUCT_SAGA
} from './rootsaga/UserSaga';

function* rootSaga() {
    yield all([
        HANDLE_GET_PRODUCT_SAGA(),
        HANDLE_POST_PRODUCT_SAGA(),
        HANDLE_DELETE_PRODUCT_SAGA(),
        HANDLE_UPDATE_PRODUCT_SAGA(),

        HANDLE_GET_CATEGORY_SAGA(),
        HANDLE_POST_CATEGORY_SAGA(),
        HANDLE_DELETE_CATEGORY_SAGA(),
        HANDLE_UPDATE_CATEGORY_SAGA(),

        HANDLE_GET_BRAND_SAGA(),
        HANDLE_POST_BRAND_SAGA(),
        HANDLE_DELETE_BRAND_SAGA(),
        HANDLE_UPDATE_BRAND_SAGA(),

        HANDLE_GET_MODEL_SAGA(),
        HANDLE_POST_MODEL_SAGA(),
        HANDLE_DELETE_MODEL_SAGA(),
        HANDLE_UPDATE_MODEL_SAGA(),
    ]);
}

export default rootSaga;